import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster"
import {SpeedInsights} from "@vercel/speed-insights/next"
import "./globals.css";



const geistMono = localFont({
  src: "./fonts/ethnocentric_rg.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {

  title: "Anti Ai 3.0",
  description: "Generated by create next app",

  icons:{
    icon: "/static/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body
        className={`${geistMono.variable} antialiased overflow-y-scroll`}
      >
        {children}
        <Toaster />
        <SpeedInsights/>
      </body>
    </html>
  );
}
